# Generated by Django 5.2.13 on 2026-04-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HazardEdge',
            fields=[
                ('asset_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('composite_hazard', models.FloatField(default=0)),
                ('hazard_flood', models.FloatField(default=0)),
                ('hazard_strike', models.FloatField(default=0)),
                ('hazard_accident', models.FloatField(default=0)),
                ('alert_level', models.CharField(default='LOW', max_length=20)),
                ('any_trigger', models.BooleanField(default=False)),
                ('travel_time_hr', models.FloatField(null=True)),
                ('strike_index', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('geometry_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hazard_edges_latest',
            },
        ),
        migrations.CreateModel(
            name='HazardNode',
            fields=[
                ('asset_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('composite_hazard', models.FloatField(default=0)),
                ('hazard_flood', models.FloatField(default=0)),
                ('hazard_cyclone', models.FloatField(default=0)),
                ('hazard_strike', models.FloatField(default=0)),
                ('hazard_accident', models.FloatField(default=0)),
                ('alert_level', models.CharField(default='LOW', max_length=20)),
                ('any_trigger', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('geometry_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hazard_nodes_latest',
            },
        ),
    ]
