# Generated by Django 5.2.13 on 2026-04-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=50)),
                ('total_nodes', models.IntegerField(default=0)),
                ('total_edges', models.IntegerField(default=0)),
                ('triggered_nodes', models.IntegerField(default=0)),
                ('triggered_edges', models.IntegerField(default=0)),
                ('critical_nodes', models.IntegerField(default=0)),
                ('high_nodes', models.IntegerField(default=0)),
                ('flood_triggered_nodes', models.IntegerField(default=0)),
                ('cyclone_triggered_nodes', models.IntegerField(default=0)),
                ('strike_triggered_nodes', models.IntegerField(default=0)),
                ('accident_triggered_nodes', models.IntegerField(default=0)),
                ('max_composite_hazard', models.FloatField(default=0)),
                ('avg_composite_hazard', models.FloatField(default=0)),
                ('top_risk_asset', models.CharField(blank=True, max_length=255, null=True)),
                ('hazard_flood_status', models.CharField(default='NOT_RUN', max_length=100)),
                ('hazard_cyclone_status', models.CharField(default='NOT_RUN', max_length=100)),
                ('hazard_strike_status', models.CharField(default='NOT_RUN', max_length=100)),
                ('hazard_accident_status', models.CharField(default='NOT_RUN', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hazard_kpi_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='hazardedge',
            name='geometry_json',
        ),
        migrations.RemoveField(
            model_name='hazardedge',
            name='travel_time_hr',
        ),
        migrations.RemoveField(
            model_name='hazardnode',
            name='geometry_json',
        ),
        migrations.AddField(
            model_name='hazardedge',
            name='hazard_cyclone',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hazardedge',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hazardedge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hazardnode',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hazardnode',
            name='lon',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hazardnode',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hazardnode',
            name='node_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hazardnode',
            name='trigger_accident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hazardnode',
            name='trigger_cyclone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hazardnode',
            name='trigger_flood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hazardnode',
            name='trigger_strike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hazardnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hazardedge',
            name='timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hazardnode',
            name='timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
