# Generated by Django 5.2.13 on 2026-04-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard', '0002_add_hazard_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardEdgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=255)),
                ('composite_hazard', models.FloatField()),
                ('alert_level', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Hazard Edge Log',
                'verbose_name_plural': 'Hazard Edge Logs',
                'db_table': 'hazard_edges_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HazardNodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=255)),
                ('composite_hazard', models.FloatField()),
                ('alert_level', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Hazard Node Log',
                'verbose_name_plural': 'Hazard Node Logs',
                'db_table': 'hazard_nodes_log',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='hazardedge',
            options={'managed': False, 'verbose_name': 'Hazard Edge (Latest)', 'verbose_name_plural': 'Hazard Edges (Latest)'},
        ),
        migrations.AlterModelOptions(
            name='hazardkpi',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Hazard KPI', 'verbose_name_plural': 'Hazard KPIs'},
        ),
        migrations.AlterModelOptions(
            name='hazardnode',
            options={'managed': False, 'verbose_name': 'Hazard Node (Latest)', 'verbose_name_plural': 'Hazard Nodes (Latest)'},
        ),
    ]
