# Generated by Django 5.2.13 on 2026-04-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEdge',
            fields=[
                ('asset_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('from_node', models.CharField(max_length=255)),
                ('to_node', models.CharField(max_length=255)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('length_km', models.FloatField(default=0)),
                ('risk_flood', models.FloatField(default=0)),
                ('risk_cyclone', models.FloatField(default=0)),
                ('risk_strike', models.FloatField(default=0)),
                ('risk_accident', models.FloatField(default=0)),
                ('composite_risk', models.FloatField(default=0)),
                ('network_risk', models.FloatField(default=0)),
                ('risk_tier', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=20)),
                ('is_critical_link', models.BooleanField(default=False)),
                ('timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Risk Edge (Latest)',
                'verbose_name_plural': 'Risk Edges (Latest)',
                'db_table': 'risk_edges_latest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskEdgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=255)),
                ('composite_risk', models.FloatField()),
                ('risk_tier', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Risk Edge Log',
                'verbose_name_plural': 'Risk Edge Logs',
                'db_table': 'risk_edges_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=50)),
                ('total_nodes', models.IntegerField(default=0)),
                ('total_edges', models.IntegerField(default=0)),
                ('critical_nodes', models.IntegerField(default=0)),
                ('high_nodes', models.IntegerField(default=0)),
                ('medium_nodes', models.IntegerField(default=0)),
                ('low_nodes', models.IntegerField(default=0)),
                ('max_composite_risk', models.FloatField(default=0)),
                ('avg_composite_risk', models.FloatField(default=0)),
                ('num_chokepoints', models.IntegerField(default=0)),
                ('top_chokepoint', models.CharField(blank=True, max_length=255, null=True)),
                ('num_critical_links', models.IntegerField(default=0)),
                ('scenario_sensitivity', models.FloatField(default=0, help_text='Sensitivity to network disruption')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Risk KPI',
                'verbose_name_plural': 'Risk KPIs',
                'db_table': 'risk_kpis_log',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskNode',
            fields=[
                ('asset_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('node_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('hazard_flood', models.FloatField(default=0)),
                ('hazard_cyclone', models.FloatField(default=0)),
                ('hazard_strike', models.FloatField(default=0)),
                ('hazard_accident', models.FloatField(default=0)),
                ('exposure_flood', models.FloatField(default=0)),
                ('exposure_cyclone', models.FloatField(default=0)),
                ('exposure_strike', models.FloatField(default=0)),
                ('exposure_accident', models.FloatField(default=0)),
                ('vulnerability_flood', models.FloatField(default=0)),
                ('vulnerability_cyclone', models.FloatField(default=0)),
                ('vulnerability_strike', models.FloatField(default=0)),
                ('vulnerability_accident', models.FloatField(default=0)),
                ('risk_flood', models.FloatField(default=0)),
                ('risk_cyclone', models.FloatField(default=0)),
                ('risk_strike', models.FloatField(default=0)),
                ('risk_accident', models.FloatField(default=0)),
                ('composite_risk', models.FloatField(default=0, help_text='0-1, aggregated multi-hazard risk')),
                ('network_risk', models.FloatField(default=0, help_text='Risk weighted by centrality')),
                ('risk_tier', models.CharField(choices=[('CRITICAL', 'Critical - Immediate action required'), ('HIGH', 'High - Close monitoring'), ('MEDIUM', 'Medium - Watch list'), ('LOW', 'Low - Acceptable')], default='LOW', max_length=20)),
                ('is_chokepoint', models.BooleanField(default=False, help_text='High risk + high centrality')),
                ('timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Risk Node (Latest)',
                'verbose_name_plural': 'Risk Nodes (Latest)',
                'db_table': 'risk_nodes_latest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskNodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=255)),
                ('composite_risk', models.FloatField()),
                ('network_risk', models.FloatField()),
                ('risk_tier', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Risk Node Log',
                'verbose_name_plural': 'Risk Node Logs',
                'db_table': 'risk_nodes_log',
                'managed': False,
            },
        ),
    ]
