# Generated by Django 5.2.13 on 2026-04-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_nodes', models.IntegerField()),
                ('total_edges', models.IntegerField()),
                ('triggered_nodes', models.IntegerField(default=0)),
                ('triggered_edges', models.IntegerField(default=0)),
                ('critical_nodes', models.IntegerField(default=0)),
                ('high_nodes', models.IntegerField(default=0)),
                ('max_composite_hazard', models.FloatField(default=0)),
                ('avg_composite_hazard', models.FloatField(default=0)),
                ('top_risk_asset', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'kpis_log',
            },
        ),
        migrations.CreateModel(
            name='NetworkEdge',
            fields=[
                ('asset_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('edge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('from_node', models.CharField(max_length=255)),
                ('to_node', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=50)),
                ('road_type', models.CharField(blank=True, max_length=50, null=True)),
                ('length_km', models.FloatField()),
                ('avg_speed_kmh', models.IntegerField()),
                ('travel_time_hr', models.FloatField()),
                ('capacity_index', models.IntegerField(default=3)),
                ('edge_betweenness', models.FloatField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'network_edges',
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('asset_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('node_type', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('betweenness_centrality', models.FloatField(default=0)),
                ('degree_centrality', models.FloatField(default=0)),
                ('closeness_centrality', models.FloatField(default=0)),
                ('eigenvector_centrality', models.FloatField(default=0)),
                ('importance_index', models.IntegerField(default=1)),
                ('handling_capacity_index', models.IntegerField(default=1)),
                ('redundancy_index', models.IntegerField(default=0)),
                ('geometry_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'network_nodes',
            },
        ),
    ]
