# Generated by Django 5.2.13 on 2026-04-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KPILog',
        ),
        migrations.AlterModelOptions(
            name='networkedge',
            options={'managed': False, 'verbose_name': 'Network Edge', 'verbose_name_plural': 'Network Edges'},
        ),
        migrations.AlterModelOptions(
            name='networknode',
            options={'managed': False, 'verbose_name': 'Network Node', 'verbose_name_plural': 'Network Nodes'},
        ),
    ]
